"""dbreset

Revision ID: 2b846f750f65
Revises: da1c5ad2052b
Create Date: 2022-07-29 14:48:04.436965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b846f750f65'
down_revision = 'da1c5ad2052b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('pic', sa.BLOB(), nullable=True))
    op.add_column('suggestions', sa.Column('pic', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggestions', 'pic')
    op.drop_column('books', 'pic')
    # ### end Alembic commands ###
