"""next1

Revision ID: 415c4999f2d2
Revises: 474930ab5f25
Create Date: 2022-07-29 05:08:17.536547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415c4999f2d2'
down_revision = '474930ab5f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('pic', sa.String(), nullable=True))
    op.add_column('suggestions', sa.Column('pic', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profpic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profpic')
    op.drop_column('suggestions', 'pic')
    op.drop_column('books', 'pic')
    # ### end Alembic commands ###
