"""next

Revision ID: 474930ab5f25
Revises: c3ba8a748323
Create Date: 2022-07-29 05:06:53.763468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '474930ab5f25'
down_revision = 'c3ba8a748323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'pic')
    op.drop_column('suggestions', 'pic')
    op.drop_column('users', 'profpic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profpic', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('suggestions', sa.Column('pic', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('pic', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
