"""final db change

Revision ID: 4af2964f208a
Revises: f6da160a647d
Create Date: 2022-09-21 13:54:24.506101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af2964f208a'
down_revision = 'f6da160a647d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'read',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'read',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
