"""dbreset

Revision ID: 8a52126cef35
Revises: f19a22109dc8
Create Date: 2022-07-29 14:22:29.145494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a52126cef35'
down_revision = 'f19a22109dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'pic')
    op.drop_column('suggestions', 'pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestions', sa.Column('pic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('pic', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
