"""Second Migration

Revision ID: c3ba8a748323
Revises: fb72a1871b25
Create Date: 2022-07-25 18:51:21.634676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ba8a748323'
down_revision = 'fb72a1871b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('pic', sa.LargeBinary(), nullable=True))
    op.add_column('suggestions', sa.Column('pic', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('profpic', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profpic')
    op.drop_column('suggestions', 'pic')
    op.drop_column('books', 'pic')
    # ### end Alembic commands ###
