"""boolean change2s

Revision ID: d6f6e09d23e7
Revises: f5b4920cff57
Create Date: 2022-08-17 21:40:25.941667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f6e09d23e7'
down_revision = 'f5b4920cff57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
