"""dbreset

Revision ID: d9293b57a7f2
Revises: 8a52126cef35
Create Date: 2022-07-29 14:26:12.157303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9293b57a7f2'
down_revision = '8a52126cef35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('pic', sa.LargeBinary(), nullable=True))
    op.add_column('suggestions', sa.Column('pic', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggestions', 'pic')
    op.drop_column('books', 'pic')
    # ### end Alembic commands ###
