"""dbreset

Revision ID: da1c5ad2052b
Revises: d9293b57a7f2
Create Date: 2022-07-29 14:46:49.270638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da1c5ad2052b'
down_revision = 'd9293b57a7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'pic')
    op.drop_column('suggestions', 'pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestions', sa.Column('pic', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('pic', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
