"""about

Revision ID: f19a22109dc8
Revises: 415c4999f2d2
Create Date: 2022-07-29 05:43:22.144932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19a22109dc8'
down_revision = '415c4999f2d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('about', sa.String(), nullable=True))
    op.add_column('suggestions', sa.Column('about', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggestions', 'about')
    op.drop_column('books', 'about')
    # ### end Alembic commands ###
