"""final db change

Revision ID: f3991660c72a
Revises: 868e7c6ae760
Create Date: 2022-09-21 13:55:48.297953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3991660c72a'
down_revision = '868e7c6ae760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'read')
    # ### end Alembic commands ###
